#! /bin/sh
# Copyright ⓒ 2013 Jason Lingle
#
# This file is part of Soliloquy.
#
# Soliloquy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Soliloquy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Soliloquy.  If not, see <http://www.gnu.org/licenses/>.

if test "$#" != "1" || \
   test "$1" = "-h" || \
   test "$1" = "-?" || \
   test "$1" = "--help"; then
    echo "Usage: $0 symbol" >&2
    echo "Shows the documentation for _symbol_." >&2
    test "$#" = "1"
    exit $?
fi

symbol=`echo "$1" | sed 's/$[a-zA-Z0-9]*_//'`

PATTERN='SYMBOL:[^\a]*\$[a-zA-Z0-9]+_'"$symbol"'\\b[^\a]*\a([^\a]+|\a[ \t]*[^ \t\a])+'
# Because escape sequences are not supported in brackets
PATTERN=`echo "$PATTERN"`
find `dirname $0` -name '*.c' | (while read source; do
    if doc=`<$source sed 's:\*/:\n:g' | tr '\n' '\a' | grep -Eo "$PATTERN"`; then
        echo "As documented in $source:"
        echo "$doc" | tr '\a' '\n'
    fi
done)
