#! /bin/sh
# Copyright ⓒ 2013 Jason Lingle
#
# This file is part of Soliloquy.
#
# Soliloquy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Soliloquy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Soliloquy.  If not, see <http://www.gnu.org/licenses/>.

if test "x$*" = "x"; then
    echo "Usage: $0 symbol [...]" >&2
    echo "Find brief definitions of the listed symbols." >&2
    echo "Symbol names may have their leading dollar and type omitted." >&2
    exit 255
fi

while test "x$1" != "x"; do
    sym=$1
    shift
    sym=`echo $sym | sed 's/$[a-zA-Z]*_//'`
    found=no
    find `dirname $0` -name '*.c' -exec \
        grep -EA1 "SYMBOL:.*\\$[a-zA-Z]+_$sym\\b" '{}' \; | \
        grep -Fv SYMBOL: | (while read line; do
            found=yes
            echo "$sym: $line"
        done; test "$found" = "yes") && \
            found=yes

    if test "$found" = "no"; then
        exit_status=1
        echo "$sym: nothing appropriate"
    fi
done

exit $exit_status
